[book]
authors = ["Aten"]
language = "zh_CN"
multilingual = false
src = "src"
title = "Substrate Contracts Book"

[language.en_US]
name = "English"

[language.zh_CN]
name = "中文"
title = "Substrate 合约书"